### PR TITLE
Move lexers to correct folders

### PR DESCRIPTION
**Pull request by gandarez**
This PR moves `hlb` and `qml` lexers to correct folders.

### CODE REVIEW

**Comment by dron22** [comment]
That's a good question, if we should move these. I mean they should be in the subfolders, but for the functionality of chroma inside wakatime-cli it doesn't make a difference, as they are registered with `internal.Register`. Keeping them where they are could prevent merge conflicts on upstream changes.

What is your opinion here?

**Comment by gandarez** [comment]
I think we're trying to fix a problem on upstream into our fork. I'll open the same PR there and see what they say.

**Comment by gandarez** [comment]
https://github.com/alecthomas/chroma/pull/434

**Comment by dron22** [comment]
> I think we're trying to fix a problem on upstream into our fork. I'll open the same PR there and see what they say.

Perfect, this is the right thing to do :+1:

**Comment by gandarez** [comment]
@dron22 PR merged on upstream. Should we proceed with this one?

**Comment by dron22** [comment]
Great you brought it into the upstream :muscle: 

The right way to proceed here would be to rebase our fork to upstream master, once a new version is created. I guess we should wait with this, until we got the lexers ported. Otherwise we will risk a lot of conflicts.

If we proceed like this, we can close this PR without merging.

**Comment by dron22** [comment]
> Actually we don't need to wait for this specific commit because I cherry picked it from our fork and the same one got merged. So if we merge it to our repo, when rebasing no error will happen because of it. The commit sha and changes are the same.

Alright let's merge it :+1:

**Comment by dron22** [comment]
> Actually we don't need to wait for this specific commit because I cherry picked it from our fork and the same one got merged. So if we merge it to our repo, when rebasing no error will happen because of it. The commit sha and changes are the same.

Sounds good. Let's merge it :+1:

**Review by dron22 — APPROVED** [review]

**Pull request merged**
