### PR TITLE
O lexers

### LINKED ISSUE #214: Port missing O lexers
Port missing `o` lexers to Chroma.

- objdump
- Objective-J
- ODIN
- Ooc
- Opa
- OpenEdge ABL

### PR DESCRIPTION
**Pull request by gandarez**
Port missing `o` lexers to Chroma.

- objdump
- ODIN
- Ooc
- Opa

Closes https://github.com/wakatime/wakatime-cli/issues/214

### CODE REVIEW

**Review by dron22 — APPROVED** [review]
LGTM

**Review by dron22 — CHANGES_REQUESTED** [review]
When reviewing priorities PR (#102), I realized, that `ObjectiveC++` lexer is also missing. We should add this here as well.

**Comment by gandarez** [comment]
@dron22 I added Objective-C++ basic structure and also couldn't find any real example to match both regexes that C++ tests.

**Comment by dron22** [comment]
@gandarez I found some here (at least for `include`: http://philjordan.eu/article/mixing-objective-c-c++-and-objective-c++

For example:
```
#include "Widget.hpp"
#import "ABCWidget.h"
namespace abc
{
  struct WidgetImpl
  {
    ABCWidget* wrapped;
  };
  Widget::Widget() :
    impl(new WidgetImpl)
  {
    impl->wrapped = [[ABCWidget alloc] init];
  }
  Widget::~Widget()
  {
    if (impl)
      [impl->wrapped release];
    delete impl;
  }
  void Widget::Reticulate()
  {
    [impl->wrapped reticulate];
  }
}
```

**Comment by gandarez** [comment]
> @gandarez I found some here (at least for `include`: http://philjordan.eu/article/mixing-objective-c-c++-and-objective-c++
> 
> For example:
> 
> ```
> #include "Widget.hpp"
> #import "ABCWidget.h"
> namespace abc
> {
>   struct WidgetImpl
>   {
>     ABCWidget* wrapped;
>   };
>   Widget::Widget() :
>     impl(new WidgetImpl)
>   {
>     impl->wrapped = [[ABCWidget alloc] init];
>   }
>   Widget::~Widget()
>   {
>     if (impl)
>       [impl->wrapped release];
>     delete impl;
>   }
>   void Widget::Reticulate()
>   {
>     [impl->wrapped reticulate];
>   }
> }
> ```

It doesn't work for the C++ regexes
- `#include <[a-z_]+>`
- `using namespace `

**Comment by dron22** [comment]
Alright, so this is similar to mql. It seems text analysis is flawed. Do you want to create an issue in pygments?

**Review by dron22 — APPROVED** [review]

**Comment by gandarez** [comment]
> Alright, so this is similar to mql. It seems text analysis is flawed. Do you want to create an issue in pygments?

I'll manage it.

**Pull request merged**
