### PR TITLE
Add set text analyzer for actionscript lexer

### PR DESCRIPTION
**Pull request by gandarez**
This PR ports pygments actionscript and actionscript3 text analysis to chroma/go. Original code can be found at: https://github.com/pygments/pygments/blob/master/pygments/lexers/actionscript.py#L198

https://github.com/wakatime/wakatime-cli/issues/82

### CODE REVIEW

**Review by dron22 — CHANGES_REQUESTED** [review]
tests are failing

**Comment by gandarez** [comment]
@dron22 fixed broken tests.

**Review by dron22 — CHANGES_REQUESTED** [review]
We could have one or two more test examples, as the regex will also accept whitespace characters around the colon. E.g. `value: string` in:
```actionscript
setStatus(value: string) {
    this._output = value;
}
```

**Comment by dron22** [comment]
Another example could be upper case letters on both sides of the colon:
```actionscript
public const RENDERER_MESSAGE:String = "rendererMessage";
```

**Comment by gandarez** [comment]
@dron22 I added more tests as you pointed out. Tks

**Review by dron22 — APPROVED** [review]
:+1:

**Pull request merged**
